######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 2 18:08:35 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
